"""add_pii_redaction_fields

Revision ID: 2c07da48b63d
Revises: d662df559ac5
Create Date: 2026-05-02 01:26:27.677923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c07da48b63d'
down_revision: Union[str, None] = 'd662df559ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('pii_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{"enabled": true, "enabled_types": ["phone", "email", "ssn", "credit_card"], "redaction_token": "***REDACTED***", "log_redactions": true, "names_enabled": false}', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('pii_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('redacted_type', sa.String(length=50), nullable=False),
    sa.Column('redacted_value_hash', sa.String(length=64), nullable=False),
    sa.Column('redacted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_audit_logs_id'), 'pii_audit_logs', ['id'], unique=False)
    op.add_column('evaluations', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('pii_redacted', sa.Boolean(), nullable=True))
    op.add_column('evaluations', sa.Column('redacted_count', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('redacted_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evaluations', sa.Column('redaction_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evaluations', sa.Column('original_transcript_hash', sa.String(length=64), nullable=True))
    # op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_foreign_key(None, 'evaluations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('lobs', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # op.create_index(op.f('ix_lobs_id'), 'lobs', ['id'], unique=False)
    op.create_foreign_key(None, 'lobs', 'tenants', ['tenant_id'], ['id'])
    # op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # op.drop_constraint('users_email_key', 'users', type_='unique')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_index(op.f('ix_users_id'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'tenant_id')
    # op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_constraint(None, 'lobs', type_='foreignkey')
    # op.drop_index(op.f('ix_lobs_id'), table_name='lobs')
    op.drop_column('lobs', 'tenant_id')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    # op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_column('evaluations', 'original_transcript_hash')
    op.drop_column('evaluations', 'redaction_log')
    op.drop_column('evaluations', 'redacted_types')
    op.drop_column('evaluations', 'redacted_count')
    op.drop_column('evaluations', 'pii_redacted')
    op.drop_column('evaluations', 'tenant_id')
    op.drop_index(op.f('ix_pii_audit_logs_id'), table_name='pii_audit_logs')
    op.drop_table('pii_audit_logs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
