"""add_human_observations

Revision ID: 4411adc244ca
Revises: 8254e30078c7
Create Date: 2026-05-15 09:20:10.153659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4411adc244ca'
down_revision: Union[str, None] = '8254e30078c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('human_observations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'human_observations')
    # ### end Alembic commands ###
