"""add_dynamic_ai_columns

Revision ID: 5471ab1b1a99
Revises: 3a4c3d1801a4
Create Date: 2026-05-15 08:34:19.540679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5471ab1b1a99'
down_revision: Union[str, None] = '3a4c3d1801a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('ai_predictions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evaluations', sa.Column('ai_reasoning_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evaluations', sa.Column('initial_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'initial_score')
    op.drop_column('evaluations', 'ai_reasoning_json')
    op.drop_column('evaluations', 'ai_predictions_json')
    # ### end Alembic commands ###
