"""Initial migration

Revision ID: d662df559ac5
Revises: 
Create Date: 2026-05-01 11:28:05.074926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd662df559ac5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('criteria_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_lobs_id'), 'lobs', ['id'], unique=False)
    
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('blacklisted_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='admin', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=True),
    sa.Column('full_transcript', sa.Text(), nullable=True),
    sa.Column('detected_language', sa.String(length=50), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('ttca_seconds', sa.Integer(), nullable=True),
    sa.Column('ttch_seconds', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('had_error', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('greeting_ai', sa.String(length=10), nullable=True),
    sa.Column('hipaa_verification_ai', sa.String(length=10), nullable=True),
    sa.Column('resolve_concern_ai', sa.String(length=10), nullable=True),
    sa.Column('pci_compliance_ai', sa.String(length=10), nullable=True),
    sa.Column('call_closing_ai', sa.String(length=10), nullable=True),
    sa.Column('professionalism_ai', sa.String(length=10), nullable=True),
    sa.Column('call_management_ai', sa.String(length=10), nullable=True),
    sa.Column('documentation_ai', sa.String(length=10), nullable=True),
    sa.Column('greeting_reasoning', sa.Text(), nullable=True),
    sa.Column('hipaa_verification_reasoning', sa.Text(), nullable=True),
    sa.Column('resolve_concern_reasoning', sa.Text(), nullable=True),
    sa.Column('pci_compliance_reasoning', sa.Text(), nullable=True),
    sa.Column('call_closing_reasoning', sa.Text(), nullable=True),
    sa.Column('professionalism_reasoning', sa.Text(), nullable=True),
    sa.Column('call_management_reasoning', sa.Text(), nullable=True),
    sa.Column('greeting', sa.String(length=10), nullable=True),
    sa.Column('hipaa_verification', sa.String(length=10), nullable=True),
    sa.Column('resolve_concern', sa.String(length=10), nullable=True),
    sa.Column('pci_compliance', sa.String(length=10), nullable=True),
    sa.Column('call_closing', sa.String(length=10), nullable=True),
    sa.Column('professionalism', sa.String(length=10), nullable=True),
    sa.Column('call_management', sa.String(length=10), nullable=True),
    sa.Column('documentation', sa.String(length=10), nullable=True),
    sa.Column('lob_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_lobs_id'), table_name='lobs')
    op.drop_table('lobs')
    # ### end Alembic commands ###
